#!/bin/bash

set -e

BUILD=build
version=$(cat VERSION)
size=$(du -csh package/ | sed '1!d' | grep -oe "^[0-9]*")

rm -Rf $BUILD
mkdir -p $BUILD/release

echo "Building version $version..."

# Architectures: i386, amd64, armle

cp -R package/* $BUILD
sed 's/{{version}}/'${version}'/g;s/{{size}}/'${size}'/g' package/DEBIAN/control > $BUILD/DEBIAN/control

fakeroot dpkg-deb -b -z9 $BUILD $BUILD/release

echo done
